### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by kamicut** [iranopendata/catalog#1]
A dataset is added to the catalog as a [TOML](https://github.com/toml-lang/toml) file with metadata fields, the spec is adapted from [Data Packages](http://specs.frictionlessdata.io/data-packages/) for interoperability. [This](http://data.okfn.org/data/core/gdp/datapackage.json) is a good example of a data package, and OKFN has [built](http://frictionlessdata.io/tools/) a lot of tools in the ecosystem. TOML is chosen for readability. 
## Metadata
- `name`: alphanumeric string, can contain `-`, `_`, `.`
- `resources`: array of data objects that follow the resource information spec below
- `title`: short sentence that describes the dataset
- `description`: a longer description of the dataset
- `keywords`: an array of keywords
- `license`: string that indicates the license
- `author`: object that can contain the fields `name`, `email`, `web`
- `homepage`: URL to the dataset's web site
## Resource Information
- `url`: URL to the source
- `name`: alphanumeric string, can contain `-`, `_`, `.`
- `title`: short sentence that describes the resource
- `description`: a longer description of the resource
- `format`: the file extension

If the format is tabular (CSV), these are additional fields:
- `sample_url`: a sample of the resource
- `schema`: an array of objects that have the keys "name" and "type" (we can make this more complete if we follow the [JSON table schema](http://specs.frictionlessdata.io/json-table-schema/))
## Example

``` toml
name = "gdp"
title = "Country, Regional and World GDP (Gross Domestic Product)"
description = "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."
license = "PDDL-1.0"
keywords = [ "GDP", "World", "Gross Domestic Product", "Time series"]

[[resources]]
  name = "gdp"
  url = "https://raw.github.com/datasets/gdp/master/data/gdp.csv"
  format = "csv"

  [[resources.schema]]
  name = "Country Name"
  type = "string"

  [[resources.schema]]
  name = "Country Code"
  type = "string"

  [[resources.schema]]
  name = "Year"
  type = "date"

  [[resources.schema]]
  name = "Value"
  type = "number"

[[resources]]
  name = "gdp-market-prices"
  url = "http://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.CD?downloadformat=xml"
  title = "GDP at market prices (current US$)"
  format = "XML"
```

We should define what fields are required and which ones are optional. Are there anymore fields which we could need?

**Comment by menayat** [comment]
I suggest to add the following fields to the metadata:
- **release date**: the know date for the publication of source dataset
- **update/ modification date**: the last modification date (generated automatically by the validator)
- **period Of time**: the period of time covered by the dataset
- **update frequency**: the expected/know frequency of update
- **maintainer**: the details of entity responsible for scrapping/maintaining the dataset, it can be an object that can contain the fields name, email, web
- **simple url**: defining a shortened url for a dataset that can be displayed on the site 

I also suggest to keep the dates in metadata in gregorian calendar. The dates inside the datasets can be in Persian calendar.

In terms of bilingual fields, all the fields will be bilingual _apart_ from:

**Metadata**
- resources
- homepage
- release date
- update/ modification date
- simple url

**Resource Information**
- url
- format
- sample_url

**Comment by kamicut** [comment]
@menayat thanks for contributing, those sound like great additions. I have a few questions that I've been thinking about:
- Should we indicate which keys are optional/required? For example, I can see "title" being required, but maybe the "release date" cannot always be found.
- I'm not sure what you mean by simple URL? Is it just for display purpose? In that case we can always have the link be called "Download" or "View Source Data" and the link be clickable to visit the site / download the content. Unless you envision some other way to share / visualize the link?
- For bilingual and adding from a discussion with him, we can have fields such as `title_en` and `title_fa`. What are your thoughts on having a default key such as `title` and what language should that be in? We can also not have a default key, and the validation enforce that there should be a language (`_en`) attached to those keys. 
- A bilingual key **must** have both language keys: What happens in the validation pipeline if one of the keys doesn't have a bilingual counterpart? Should the validation fail until the maintainer translates all the keys? If not, what would the website text be for that key (e.g: "No content", "Translation needed", etc).

**Comment by menayat** [comment]
@kamicut Thanks for reviewing and the questions. Please see my responses below:
- I agree that there might not be any input for some of the fields. My suggestion is to leave them mandatory anyway and entering "unknown". For instance if we don't know the 'release date' or 'update frequency', this way we can communicate to the user that we couldn't find the value for these fields rather, than it being an omission from our side.
- By 'simple url', I mean what is going to be displayed in the url for the individual dataset page. I thought it would be better to have a human readable, properly formatted url schema, rather than having a numerical ID or a chopped title. It can also be used in the API calls.
- It's hard to decide on the language syntax as I don't know what the potential implication might. However, now I have a slight preference for having the translations inside each field like:

```
"titles": {
  "en": "dataset title",
  "fa": "عنوان دادهt"
}

```
- I think all the fields should be mandatory for the both languages. A dataset should not be validated until all the metadata fields are added in both languages. We can revise this policy later on.

And one question:
- Do we need to have the homepage as a field if we are capturing the web address in the author's field?

**Comment by menayat** [comment]
@kamicut An afterthought: we don't need simple url. The field "title" will do the job.

**Comment by kamicut** [comment]
@menayat Ah, I get it now; yes, we can generate the URL ourselves using the title or some other identifier. I was thinking that the author would be the name of the organization providing the dataset, distinct from the organization's website.

**Comment by menayat** [comment]
@kamicut So can we say that the _web_ in the _author_ field is a reference to the Organization website and the _homepage_ is the link to the original dataset?

**Comment by kamicut** [comment]
@menayat correct, I thought that those could potentially be two different websites; however I'm not sure if the case arises in practice. Is it your opinion that we should simplify it and keep it one URL?

**Comment by menayat** [comment]
@kamicut Yes, it will be highly unlikely. We can keep the _author_ to just capture the name and the have the link to the dataset in the _homepage_.

**Comment by kamicut** [comment]
Here's an updated spec example using these additions: Title will be bilingual, but 'name' will be the short title that will be used in the URL, so it doesn't need to be bilingual. I kept keywords, license and author as a single language for simplicity but we can change that too. If a resource is a CSV, I kept the header fields as a single language as well.

Human Readable TOML:

``` toml
license = "PDDL-1.0"
keywords = [ "GDP", "World", "Gross Domestic Product", "Time series"]
created_at = "2016-07-27T21:36:26.161Z"
updated_at = "2016-07-27T21:36:26.161Z"
author = "Organization Name"
homepage = "http://example.com/dataset/"

name = "gdp"

[[title]]
lang = "en"
title = "Country, Regional and World GDP (Gross Domestic Product)"

[[title]]
lang = "fa"
title = "Country, Regional and World GDP (Gross Domestic Product)"

[[description]]
lang = "fa"
description = "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."

[[description]]
lang = "en"
description = "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."


[[resources]]

  url = "https://raw.github.com/datasets/gdp/master/data/gdp.csv"
  name = "gdp"

  [[resources.title]]
  lang = "en"
  title = "Country, Regional and World GDP (Gross Domestic Product)"

  [[resources.title]]
  lang = "fa"
  title = "Country, Regional and World GDP (Gross Domestic Product)"

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Country Name"
      type = "string"

      [[resources.schema.fields]]
      name = "Country Code"
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "date"

      [[resources.schema.fields]]
      name = "Value"
      type = "number"

[[resources]]
  name = "gdp-market-prices"
  url = "http://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.CD?downloadformat=xml"

  [[resources.title]]
  lang = "fa"
  text = "GDP at market prices (current US$)"

  [[resources.title]] 
  lang = "en"
  text = "GDP at market prices (current US$)"

  [resources.schema]
  format = "XML"

```

This will generate a JSON like this: 

``` json
{
  "license": "PDDL-1.0",
  "keywords": [
    "GDP",
    "World",
    "Gross Domestic Product",
    "Time series"
  ],
  "created_at": "2016-07-27T21:36:26.161Z",
  "updated_at": "2016-07-27T21:36:26.161Z",
  "author": "Organization Name",
  "homepage": "http://example.com/dataset/",
  "name": "gdp",
  "title": [
    {
      "lang": "en",
      "title": "Country, Regional and World GDP (Gross Domestic Product)"
    },
    {
      "lang": "fa",
      "title": "Country, Regional and World GDP (Gross Domestic Product)"
    }
  ],
  "description": [
    {
      "lang": "fa",
      "description": "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."
    },
    {
      "lang": "en",
      "description": "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."
    }
  ],
  "resources": [
    {
      "url": "https://raw.github.com/datasets/gdp/master/data/gdp.csv",
      "name": "gdp",
      "title": [
        {
          "lang": "en",
          "title": "Country, Regional and World GDP (Gross Domestic Product)"
        },
        {
          "lang": "fa",
          "title": "Country, Regional and World GDP (Gross Domestic Product)"
        }
      ],
      "schema": {
        "format": "csv",
        "fields": [
          {
            "name": "Country Name",
            "type": "string"
          },
          {
            "name": "Country Code",
            "type": "string"
          },
          {
            "name": "Year",
            "type": "date"
          },
          {
            "name": "Value",
            "type": "number"
          }
        ]
      }
    },
    {
      "name": "gdp-market-prices",
      "url": "http://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.CD?downloadformat=xml",
      "title": [
        {
          "lang": "fa",
          "text": "GDP at market prices (current US$)"
        },
        {
          "lang": "en",
          "text": "GDP at market prices (current US$)"
        }
      ],
      "schema": {
        "format": "XML"
      }
    }
  ]
}
```

I haven't written the text fields in Farsi because I don't have a Farsi keyboard 😄 , but since the spec is just text it works. cc @menayat
